### ISSUE TITLE
Fuzzy matching for assess > corp + assess > eviction links

### ISSUE THREAD

**Issue by ericrobskyhuntley** [mit-spatial-action/who-owns-mass-processing#6]
We're currently doing a literal string match (`left_join()`) to  join assessors' records to corporate records. This is too restrictive and is likely losing us some matches. The [`fuzzyjoin`](https://github.com/dgrtwo/fuzzyjoin) package is probably the ticket here, which plays along with the `tidyverse` and allows Levenshtein/cosine/other distance metrics using `stringdist_inner_join()`.

**Comment by anastasia** [comment]
a note here that using fuzzymatching methods on street and address does not seem to improve results, when running n the scoped down test dataset of Somerville.

**Comment by ericrobskyhuntley** [comment]
Yeah - and the way this is currently written, it will tend to really only affect detection of owners with fewer properties. All we need to make a match is for one name within an cosine similarity-identified group to line up with SoC db, so in larger groups (with more chances for typos, etc.) there's already a good chance we can make a match that's more reliable than what fuzzymatch would give us.

**Comment by ericrobskyhuntley** [comment]
Implemented in part - owners and companies are now matched on cosine similarity in deduplication process. Creating a separate issue for eviction linking.
